name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  mix_test:
    name: mix test (Elixir ${{matrix.elixir}} | Erlang/OTP ${{matrix.otp}})
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: 1.11.x
            otp: 23.0.3
            check_formatted: true
            warnings_as_errors: true
            credo: true
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: erlef/setup-elixir@v1.11.1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix format --check-formatted
        if: matrix.check_formatted
      - name: Install Dependencies
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get --only test
      - run: mix compile --warnings-as-errors
        if: matrix.warnings_as_errors
      - run: mix deps.unlock --check-unused
      - name: Credo
        if: matrix.credo
        run: mix credo --strict --format flycheck
      - run: mix test
